### ISSUE TITLE
Sweep: Missing js files

### ISSUE THREAD

**Issue by francisjoy** [yihong1120/Construction-Hazard-Detection#23]
### Details

Seems the UI is not working due to missing js files

**Comment by yihong1120** [comment]
Hello, which web page is causing the pagination problem? We will check it right away~

**Comment by yihong1120** [comment]
> ### Details
> Seems the UI is not working due to missing js files

Hello, which web page is causing the pagination problem? We will check it right away~

**Comment by yihong1120** [comment]
> ### Details
> Seems the UI is not working due to missing js files

Ok, we shall fix the problem by tonight~
