### ISSUE TITLE
user management not found

### ISSUE THREAD

**Issue by pipinoclaudia** [yihong1120/Construction-Hazard-Detection#25]
### Details

ERROR: build path /Users/claudiapipino/Desktop/Construction-Hazard-Detection-main/examples/user_management either does not exist, is not accessible, or is not a valid URL.

**Comment by yihong1120** [comment]
Hello~

user management  functions are not merged into [server_api](https://github.com/yihong1120/Construction-Hazard-Detection/tree/main/examples/YOLO_server_api) .  To API functions, please refer to [this file](https://github.com/yihong1120/Construction-Hazard-Detection/blob/main/examples/YOLO_server_api/routers.py), and you could reach user management functions in [this file](https://github.com/yihong1120/Construction-Hazard-Detection/blob/main/examples/YOLO_server_api/user_operation.py).

To launch the AI server, you would build the [table](https://github.com/yihong1120/Construction-Hazard-Detection/blob/main/scripts/init.sql) in database and insert a user.  By the way, we are now developing the frontend web for AI server.  Please look forward to it

Thank you, the README files are not modified.
